# Generated by Django 4.2.24 on 2025-09-20 06:08

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('ldap_uid', models.CharField(blank=True, help_text='เก็บ staffcitizenid จาก NPU API', max_length=13, null=True, unique=True, verbose_name='รหัสบัตรประชาชน')),
                ('npu_staff_id', models.CharField(blank=True, help_text='เก็บ staffid จาก NPU API', max_length=20, verbose_name='รหัสพนักงาน NPU')),
                ('prefix_name', models.CharField(blank=True, help_text='เก็บ prefixfullname จาก NPU API', max_length=20, verbose_name='คำนำหน้า')),
                ('first_name_th', models.CharField(blank=True, help_text='เก็บ staffname จาก NPU API', max_length=100, verbose_name='ชื่อ (ไทย)')),
                ('last_name_th', models.CharField(blank=True, help_text='เก็บ staffsurname จาก NPU API', max_length=100, verbose_name='นามสกุล (ไทย)')),
                ('full_name', models.CharField(blank=True, help_text='เก็บ fullname จาก NPU API', max_length=255, verbose_name='ชื่อ-สกุล (เต็ม)')),
                ('birth_date', models.DateField(blank=True, help_text='เก็บ staffbirthdate จาก NPU API', null=True, verbose_name='วันเกิด')),
                ('gender', models.CharField(blank=True, help_text='เก็บ gendernameth จาก NPU API', max_length=20, verbose_name='เพศ')),
                ('department', models.CharField(blank=True, help_text='เก็บ departmentname จาก NPU API', max_length=255, verbose_name='หน่วยงาน')),
                ('position_title', models.CharField(blank=True, help_text='เก็บ posnameth จาก NPU API', max_length=255, verbose_name='ตำแหน่ง')),
                ('staff_type', models.CharField(blank=True, help_text='เก็บ stftypename จาก NPU API', max_length=100, verbose_name='ประเภทบุคลากร')),
                ('staff_sub_type', models.CharField(blank=True, help_text='เก็บ substftypename จาก NPU API', max_length=100, verbose_name='ประเภทบุคลากรย่อย')),
                ('employment_status', models.CharField(blank=True, help_text='เก็บ stfstaname จาก NPU API', max_length=100, verbose_name='สถานะการทำงาน')),
                ('last_npu_sync', models.DateTimeField(blank=True, null=True, verbose_name='ล่าสุดที่ sync จาก NPU')),
                ('npu_last_login', models.DateTimeField(blank=True, null=True, verbose_name='login ล่าสุดจาก NPU API')),
                ('department_internal_name', models.CharField(blank=True, max_length=255, verbose_name='แผนกภายใน')),
                ('job_description', models.TextField(blank=True, verbose_name='หน้าที่รับผิดชอบ')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='อีเมลติดต่อ')),
                ('line_user_id', models.CharField(blank=True, max_length=255, verbose_name='LINE User ID')),
                ('is_document_staff', models.BooleanField(default=False, verbose_name='เจ้าหน้าที่สารบรรณ')),
                ('can_forward_documents', models.BooleanField(default=False, verbose_name='สามารถส่งต่อเอกสาร')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='วันที่อนุมัติ')),
                ('push_subscription_endpoint', models.URLField(blank=True, verbose_name='Push Endpoint')),
                ('push_subscription_keys', models.JSONField(blank=True, default=dict, verbose_name='Push Keys')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='เปิดการแจ้งเตือน')),
                ('approval_status', models.CharField(choices=[('pending', 'รอการอนุมัติ'), ('approved', 'อนุมัติแล้ว'), ('rejected', 'ปฏิเสธ'), ('suspended', 'ระงับการใช้งาน')], default='pending', max_length=20, verbose_name='สถานะการอนุมัติ')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ผู้ใช้',
                'verbose_name_plural': 'ผู้ใช้',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='ชื่อแผนก')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='รหัสแผนก')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'แผนก',
                'verbose_name_plural': 'แผนก',
            },
        ),
        migrations.CreateModel(
            name='NPUApiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ldap_uid', models.CharField(max_length=13, verbose_name='รหัสบัตรประชาชน')),
                ('action', models.CharField(choices=[('auth', 'Authentication'), ('sync', 'Data Synchronization'), ('lookup', 'User Lookup')], max_length=20, verbose_name='การดำเนินการ')),
                ('status', models.CharField(choices=[('success', 'สำเร็จ'), ('failed', 'ล้มเหลว'), ('error', 'ข้อผิดพลาด')], max_length=20, verbose_name='สถานะ')),
                ('request_data', models.JSONField(blank=True, null=True, verbose_name='ข้อมูลที่ส่งไป')),
                ('response_data', models.JSONField(blank=True, null=True, verbose_name='ข้อมูลที่ได้รับ')),
                ('error_message', models.TextField(blank=True, verbose_name='ข้อความข้อผิดพลาด')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลาที่เรียก API')),
                ('response_time_ms', models.IntegerField(blank=True, null=True, verbose_name='เวลาตอบสนอง (มิลลิวินาที)')),
            ],
            options={
                'verbose_name': 'บันทึกการเรียก NPU API',
                'verbose_name_plural': 'บันทึกการเรียก NPU API',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_fields', models.JSONField(default=list, verbose_name='ฟิลด์ที่ล็อค')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='field_locks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'การล็อคฟิลด์',
                'verbose_name_plural': 'การล็อคฟิลด์',
            },
        ),
    ]
