# Generated by Django 4.2.24 on 2025-09-23 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('receipt_create', 'สร้างใบสำคัญรับเงิน'), ('receipt_view_own', 'ดูใบสำคัญของตัวเอง'), ('receipt_edit_approve', 'อนุมัติการแก้ไขใบสำคัญรับเงิน'), ('receipt_cancel_department', 'ยกเลิกใบสำคัญของหน่วยงานตัวเอง'), ('receipt_view_department', 'ดูใบสำคัญของหน่วยงานตัวเอง'), ('receipt_view_all', 'ดูใบสำคัญรับเงินทั้งหมด'), ('receipt_export', 'ส่งออกข้อมูลใบสำคัญ'), ('user_manage', 'จัดการผู้ใช้งาน'), ('role_manage', 'จัดการบทบาทและสิทธิ์'), ('report_view', 'ดูรายงาน'), ('system_config', 'ตั้งค่าระบบ')], max_length=50, unique=True, verbose_name='ชื่อสิทธิ์')),
                ('description', models.TextField(blank=True, verbose_name='คำอธิบาย')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'สิทธิ์การใช้งาน',
                'verbose_name_plural': 'สิทธิ์การใช้งาน',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='ชื่อบทบาท')),
                ('display_name', models.CharField(max_length=100, verbose_name='ชื่อแสดง')),
                ('description', models.TextField(blank=True, verbose_name='คำอธิบาย')),
                ('department_scope', models.CharField(blank=True, help_text='หน่วยงานที่สามารถจัดการได้ (เว้นว่างหมายถึงทุกหน่วยงาน)', max_length=255, verbose_name='ขอบเขตหน่วยงาน')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(blank=True, to='accounts.permission', verbose_name='สิทธิ์')),
            ],
            options={
                'verbose_name': 'บทบาท',
                'verbose_name_plural': 'บทบาท',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='can_forward_documents',
            field=models.BooleanField(default=False, verbose_name='สามารถอนุมัติใบสำคัญรับเงิน'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_document_staff',
            field=models.BooleanField(default=False, verbose_name='เจ้าหน้าที่ออกใบสำคัญรับเงิน'),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่กำหนด')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งาน')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL, verbose_name='ผู้กำหนด')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.role', verbose_name='บทบาท')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้')),
            ],
            options={
                'verbose_name': 'บทบาทผู้ใช้',
                'verbose_name_plural': 'บทบาทผู้ใช้',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
