# Generated by Django 4.2.24 on 2025-09-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_permission_role_alter_user_can_forward_documents_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'ชื่อย่อหน่วยงาน', 'verbose_name_plural': 'ชื่อย่อหน่วยงาน'},
        ),
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.AddField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(help_text='ชื่อย่อที่จะใช้ในใบสำคัญรับเงิน', max_length=20, unique=True, verbose_name='ชื่อย่อหน่วยงาน'),
        ),
        migrations.AlterField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True, help_text='หน่วยงานที่ปิดจะไม่สามารถออกใบสำคัญได้', verbose_name='เปิดใช้งาน'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='ชื่อหน่วยงาน (จาก NPU AD)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_forward_documents',
            field=models.BooleanField(default=False, verbose_name='[DEPRECATED] สามารถอนุมัติใบสำคัญรับเงิน'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_document_staff',
            field=models.BooleanField(default=False, verbose_name='[DEPRECATED] เจ้าหน้าที่ออกใบสำคัญรับเงิน'),
        ),
    ]
