# Generated by Django 4.2.24 on 2025-09-24 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_department_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField(help_text='ปีงบประมาณไทย เช่น 2568', verbose_name='ปีงบประมาณ (พ.ศ.)')),
                ('volume_code', models.CharField(help_text='รหัสเล่ม เช่น REG68, FIN68', max_length=10, unique=True, verbose_name='รหัสเล่ม')),
                ('status', models.CharField(choices=[('active', 'ใช้งานอยู่'), ('closed', 'ปิดเล่มแล้ว'), ('archived', 'เก็บเป็นเอกสารประวัติ')], default='active', max_length=20, verbose_name='สถานะ')),
                ('is_auto_generated', models.BooleanField(default=True, help_text='สร้างโดยระบบอัตโนมัติตามปีงบประมาณ', verbose_name='สร้างอัตโนมัติ')),
                ('last_document_number', models.IntegerField(default=0, help_text='เลขที่เอกสารล่าสุดที่ออกในเล่มนี้', verbose_name='เลขที่เอกสารล่าสุด')),
                ('max_documents', models.IntegerField(default=9999, help_text='จำนวนเอกสารสูงสุดที่สามารถออกในเล่มนี้ได้', verbose_name='จำนวนเอกสารสูงสุด')),
                ('fiscal_year_start', models.DateField(verbose_name='วันเริ่มต้นปีงบประมาณ')),
                ('fiscal_year_end', models.DateField(verbose_name='วันสิ้นสุดปีงบประมาณ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไข')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='วันที่ปิดเล่ม')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_volumes', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ปิดเล่ม')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_volumes', to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้าง')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.department', verbose_name='หน่วยงาน')),
            ],
            options={
                'verbose_name': 'เล่มเอกสาร',
                'verbose_name_plural': 'เล่มเอกสาร',
                'ordering': ['-fiscal_year', 'department__name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVolumeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'สร้างเล่มใหม่'), ('document_issued', 'ออกเอกสาร'), ('closed', 'ปิดเล่ม'), ('archived', 'เก็บเป็นเอกสารประวัติ'), ('reopened', 'เปิดเล่มใหม่')], max_length=20, verbose_name='การดำเนินการ')),
                ('document_number', models.IntegerField(blank=True, help_text='เฉพาะกรณีออกเอกสาร', null=True, verbose_name='เลขที่เอกสาร')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ดำเนินการ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ดำเนินการ')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='accounts.documentvolume', verbose_name='เล่มเอกสาร')),
            ],
            options={
                'verbose_name': 'บันทึกเล่มเอกสาร',
                'verbose_name_plural': 'บันทึกเล่มเอกสาร',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='documentvolume',
            index=models.Index(fields=['fiscal_year', 'status'], name='accounts_do_fiscal__dd63aa_idx'),
        ),
        migrations.AddIndex(
            model_name='documentvolume',
            index=models.Index(fields=['department', 'fiscal_year'], name='accounts_do_departm_a2c85a_idx'),
        ),
        migrations.AddIndex(
            model_name='documentvolume',
            index=models.Index(fields=['volume_code'], name='accounts_do_volume__4a2ae5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentvolume',
            unique_together={('department', 'fiscal_year')},
        ),
    ]
