# Generated by Django 4.2.24 on 2025-09-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_documentvolume_documentvolumelog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='address_line1',
            field=models.CharField(blank=True, help_text='เช่น อาคาร เลขที่ ถนน', max_length=255, verbose_name='ที่อยู่บรรทัดที่ 1'),
        ),
        migrations.AddField(
            model_name='department',
            name='address_line2',
            field=models.CharField(blank=True, help_text='เช่น ตำบล อำเภอ จังหวัด', max_length=255, verbose_name='ที่อยู่บรรทัดที่ 2'),
        ),
        migrations.AddField(
            model_name='department',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='เบอร์โทรศัพท์'),
        ),
        migrations.AddField(
            model_name='department',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='รหัสไปรษณีย์'),
        ),
    ]
