# Generated by Django 4.2.24 on 2025-09-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_department_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='department',
            name='address_line2',
        ),
        migrations.AddField(
            model_name='department',
            name='address',
            field=models.TextField(blank=True, help_text='ที่อยู่หน่วยงานแบบครบถ้วน', verbose_name='ที่อยู่หน่วยงาน'),
        ),
    ]
