# Generated by Django 4.2.24 on 2025-09-26 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_update_department_address_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(help_text='รูปแบบ: ddmmyy/xxxx เช่น 240968/0001', max_length=15, unique=True, verbose_name='เลขที่ใบสำคัญรับเงิน')),
                ('recipient_name', models.CharField(help_text='ข้าพเจ้า ...', max_length=255, verbose_name='ชื่อผู้รับเงิน')),
                ('recipient_address', models.TextField(help_text='บ้านเลขที่ หมู่ ซอย ถนน ตำบล อำเภอ จังหวัด', verbose_name='ที่อยู่ผู้รับเงิน')),
                ('recipient_postal_code', models.CharField(blank=True, max_length=10, verbose_name='รหัสไปรษณีย์ผู้รับเงิน')),
                ('recipient_id_card', models.CharField(max_length=20, verbose_name='เลขบัตรประชาชนผู้รับเงิน')),
                ('is_loan', models.BooleanField(default=False, help_text='ถ้าเลือก จะใช้ชื่อผู้สร้างเป็นผู้จ่าย', verbose_name='เป็นการยืมเงิน')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='จำนวนเงินรวม')),
                ('total_amount_text', models.CharField(help_text='เช่น หนึ่งหมื่นบาทถ้วน', max_length=500, verbose_name='จำนวนเงินตัวหนังสือ')),
                ('status', models.CharField(choices=[('draft', 'ร่าง'), ('completed', 'เสร็จสิ้น'), ('cancelled', 'ยกเลิก')], default='draft', max_length=20, verbose_name='สถานะ')),
                ('receipt_date', models.DateField(verbose_name='วันที่ในใบสำคัญรับเงิน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้าง')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.department', verbose_name='หน่วยงาน')),
            ],
            options={
                'verbose_name': 'ใบสำคัญรับเงิน',
                'verbose_name_plural': 'ใบสำคัญรับเงิน',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='เช่น ค่าอาหารว่างและเครื่องดื่ม', max_length=255, verbose_name='ชื่อรายการ')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='เช่น 499 บาท (ถ้าไม่จำกัดให้เว้นว่าง)', max_digits=10, null=True, verbose_name='จำนวนเงินสูงสุด')),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='เช่น 1000 บาท (ถ้าไม่คงที่ให้เว้นว่าง)', max_digits=10, null=True, verbose_name='จำนวนเงินคงที่')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('category', models.CharField(blank=True, help_text='เช่น ค่าอาหาร, ค่าประกัน', max_length=100, verbose_name='หมวดหมู่')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'รายการสำเร็จรูป',
                'verbose_name_plural': 'รายการสำเร็จรูป',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='คำอธิบายรายการ', max_length=500, verbose_name='รายการ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='จำนวนเงิน')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ลำดับ')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.receipt', verbose_name='ใบสำคัญรับเงิน')),
                ('template', models.ForeignKey(blank=True, help_text='ถ้าเลือกจากรายการสำเร็จรูป', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.receipttemplate', verbose_name='รายการสำเร็จรูป')),
            ],
            options={
                'verbose_name': 'รายการใบสำคัญรับเงิน',
                'verbose_name_plural': 'รายการใบสำคัญรับเงิน',
                'ordering': ['receipt', 'order'],
            },
        ),
    ]
