# Generated by Django 4.2.24 on 2025-09-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_receipt_receipttemplate_receiptitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='qr_code_data',
            field=models.TextField(blank=True, help_text='ข้อมูลที่จะแสดงใน QR Code', verbose_name='ข้อมูล QR Code'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='verification_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash สำหรับตรวจสอบความถูกต้อง', max_length=64, unique=True, verbose_name='รหัสตรวจสอบ'),
        ),
    ]
