# Generated by Django 4.2.24 on 2025-09-27 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_qr_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptEditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(help_text='รูปแบบ: ER-yymmdd-xxxx เช่น ER-241001-0001', max_length=20, unique=True, verbose_name='เลขที่คำร้อง')),
                ('reason', models.TextField(help_text='อธิบายเหตุผลที่ต้องการแก้ไขใบสำคัญ', verbose_name='เหตุผลในการขอแก้ไข')),
                ('description', models.TextField(blank=True, help_text='อธิบายสิ่งที่ต้องการแก้ไข', verbose_name='รายละเอียดการแก้ไข')),
                ('status', models.CharField(choices=[('pending', 'รอการอนุมัติ'), ('approved', 'อนุมัติแล้ว'), ('rejected', 'ปฏิเสธ'), ('withdrawn', 'ถอนคำร้อง'), ('applied', 'ดำเนินการแล้ว')], default='pending', max_length=20, verbose_name='สถานะ')),
                ('approval_notes', models.TextField(blank=True, help_text='หมายเหตุจากผู้อนุมัติ', verbose_name='หมายเหตุการอนุมัติ')),
                ('new_recipient_name', models.CharField(blank=True, max_length=255, verbose_name='ชื่อผู้รับเงิน (ใหม่)')),
                ('new_recipient_address', models.TextField(blank=True, verbose_name='ที่อยู่ผู้รับเงิน (ใหม่)')),
                ('new_recipient_postal_code', models.CharField(blank=True, max_length=10, verbose_name='รหัสไปรษณีย์ (ใหม่)')),
                ('new_recipient_id_card', models.CharField(blank=True, max_length=20, verbose_name='เลขบัตรประชาชน (ใหม่)')),
                ('new_receipt_date', models.DateField(blank=True, null=True, verbose_name='วันที่ในใบสำคัญ (ใหม่)')),
                ('new_total_amount_text', models.CharField(blank=True, max_length=500, verbose_name='จำนวนเงินตัวหนังสือ (ใหม่)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ส่งคำร้อง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='วันที่อนุมัติ')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='วันที่ดำเนินการ')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_edit_requests', to=settings.AUTH_USER_MODEL, verbose_name='ผู้อนุมัติ')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='accounts.receipt', verbose_name='ใบสำคัญรับเงิน')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_edit_requests', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ส่งคำร้อง')),
            ],
            options={
                'verbose_name': 'คำร้องขอแก้ไขใบสำคัญรับเงิน',
                'verbose_name_plural': 'คำร้องขอแก้ไขใบสำคัญรับเงิน',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(choices=[('receipt_create', 'สร้างใบสำคัญรับเงิน'), ('receipt_view_own', 'ดูใบสำคัญของตัวเอง'), ('receipt_edit_request', 'ส่งคำร้องขอแก้ไขใบสำคัญรับเงิน'), ('receipt_edit_request_view', 'ดูคำร้องขอแก้ไขของตัวเอง'), ('receipt_edit_withdraw', 'ถอนคำร้องขอแก้ไข'), ('receipt_edit_approve', 'อนุมัติการแก้ไขใบสำคัญรับเงิน'), ('receipt_cancel_department', 'ยกเลิกใบสำคัญของหน่วยงานตัวเอง'), ('receipt_view_department', 'ดูใบสำคัญของหน่วยงานตัวเอง'), ('receipt_view_all', 'ดูใบสำคัญรับเงินทั้งหมด'), ('receipt_export', 'ส่งออกข้อมูลใบสำคัญ'), ('user_manage', 'จัดการผู้ใช้งาน'), ('role_manage', 'จัดการบทบาทและสิทธิ์'), ('report_view', 'ดูรายงาน'), ('system_config', 'ตั้งค่าระบบ')], max_length=50, unique=True, verbose_name='ชื่อสิทธิ์'),
        ),
        migrations.CreateModel(
            name='ReceiptEditRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('update', 'แก้ไข'), ('add', 'เพิ่ม'), ('delete', 'ลบ')], max_length=10, verbose_name='การดำเนินการ')),
                ('new_description', models.CharField(blank=True, max_length=500, verbose_name='รายการ (ใหม่)')),
                ('new_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='จำนวนเงิน (ใหม่)')),
                ('new_order', models.PositiveIntegerField(blank=True, null=True, verbose_name='ลำดับ (ใหม่)')),
                ('edit_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_changes', to='accounts.receipteditrequest', verbose_name='คำร้องขอแก้ไข')),
                ('original_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.receiptitem', verbose_name='รายการเดิม')),
            ],
            options={
                'verbose_name': 'รายการขอแก้ไข',
                'verbose_name_plural': 'รายการขอแก้ไข',
                'ordering': ['edit_request', 'new_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'สร้างใบสำคัญ'), ('updated', 'แก้ไขใบสำคัญ'), ('cancelled', 'ยกเลิกใบสำคัญ'), ('edit_requested', 'ส่งคำร้องขอแก้ไข'), ('edit_approved', 'อนุมัติการแก้ไข'), ('edit_rejected', 'ปฏิเสธการแก้ไข'), ('edit_applied', 'ดำเนินการแก้ไข')], max_length=20, verbose_name='การดำเนินการ')),
                ('field_name', models.CharField(blank=True, max_length=100, verbose_name='ฟิลด์ที่เปลี่ยน')),
                ('old_value', models.TextField(blank=True, verbose_name='ค่าเดิม')),
                ('new_value', models.TextField(blank=True, verbose_name='ค่าใหม่')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เปลี่ยนแปลง')),
                ('edit_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='accounts.receipteditrequest', verbose_name='คำร้องขอแก้ไข')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='accounts.receipt', verbose_name='ใบสำคัญรับเงิน')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ดำเนินการ')),
            ],
            options={
                'verbose_name': 'ประวัติการเปลี่ยนแปลง',
                'verbose_name_plural': 'ประวัติการเปลี่ยนแปลง',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='receipteditrequest',
            index=models.Index(fields=['status', 'created_at'], name='accounts_re_status_0d3da0_idx'),
        ),
        migrations.AddIndex(
            model_name='receipteditrequest',
            index=models.Index(fields=['receipt', 'status'], name='accounts_re_receipt_9bcda9_idx'),
        ),
        migrations.AddIndex(
            model_name='receipteditrequest',
            index=models.Index(fields=['requested_by', 'status'], name='accounts_re_request_60ad4b_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptchangelog',
            index=models.Index(fields=['receipt', 'action'], name='accounts_re_receipt_04f86b_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptchangelog',
            index=models.Index(fields=['edit_request'], name='accounts_re_edit_re_776d83_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptchangelog',
            index=models.Index(fields=['created_at'], name='accounts_re_created_034cf7_idx'),
        ),
    ]
