# Generated by Django 4.2.24 on 2025-09-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_edit_request_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipteditrequest',
            name='new_items_data',
            field=models.TextField(blank=True, help_text='เก็บข้อมูลรายการสินค้าในรูปแบบ JSON', verbose_name='ข้อมูลรายการสินค้าใหม่ (JSON)'),
        ),
        migrations.AddField(
            model_name='receipteditrequest',
            name='new_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='จำนวนเงินรวม (ใหม่)'),
        ),
    ]
