# Generated by Django 4.2.24 on 2025-09-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_receipteditrequest_new_items_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(choices=[('receipt_create', 'สร้างใบสำคัญรับเงิน'), ('receipt_view_own', 'ดูใบสำคัญของตัวเอง'), ('receipt_edit_request', 'ส่งคำร้องขอแก้ไขใบสำคัญรับเงิน'), ('receipt_edit_request_view', 'ดูคำร้องขอแก้ไขของตัวเอง'), ('receipt_edit_withdraw', 'ถอนคำร้องขอแก้ไข'), ('receipt_edit_approve', 'อนุมัติการแก้ไขใบสำคัญรับเงิน'), ('receipt_edit_approve_manager', 'อนุมัติการแก้ไขจาก Department Manager'), ('receipt_cancel_department', 'ยกเลิกใบสำคัญของหน่วยงานตัวเอง'), ('receipt_view_department', 'ดูใบสำคัญของหน่วยงานตัวเอง'), ('receipt_view_all', 'ดูใบสำคัญรับเงินทั้งหมด'), ('receipt_export', 'ส่งออกข้อมูลใบสำคัญ'), ('user_manage', 'จัดการผู้ใช้งาน'), ('role_manage', 'จัดการบทบาทและสิทธิ์'), ('report_view', 'ดูรายงาน'), ('system_config', 'ตั้งค่าระบบ')], max_length=50, unique=True, verbose_name='ชื่อสิทธิ์'),
        ),
    ]
