# Generated by Django 4.2.24 on 2025-09-29 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_permission_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptCancelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(help_text='รูปแบบ: CR-yymmdd-xxxx', max_length=20, unique=True, verbose_name='เลขที่คำขอยกเลิก')),
                ('cancel_reason', models.TextField(help_text='ระบุเหตุผลที่ต้องการยกเลิกใบสำคัญ', verbose_name='เหตุผลการยกเลิก')),
                ('status', models.CharField(choices=[('pending', 'รอการอนุมัติ'), ('approved', 'อนุมัติแล้ว'), ('rejected', 'ปฏิเสธ'), ('withdrawn', 'ถอนคำร้อง'), ('applied', 'ดำเนินการแล้ว')], default='pending', max_length=20, verbose_name='สถานะคำขอ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ส่งคำขอ')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='วันที่พิจารณา')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='วันที่ดำเนินการ')),
                ('approval_notes', models.TextField(blank=True, verbose_name='หมายเหตุการพิจารณา')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cancel_requests', to=settings.AUTH_USER_MODEL, verbose_name='ผู้พิจารณา')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancel_requests', to='accounts.receipt', verbose_name='ใบสำคัญรับเงิน')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_cancel_requests', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ส่งคำขอ')),
            ],
            options={
                'verbose_name': 'คำขอยกเลิกใบสำคัญ',
                'verbose_name_plural': 'คำขอยกเลิกใบสำคัญ',
                'ordering': ['-created_at'],
            },
        ),
    ]
