# Generated by Django 4.2.24 on 2025-10-01 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_receiptcancelrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_attempted', models.CharField(blank=True, help_text='เก็บไว้กรณี login_failed', max_length=150, verbose_name='Username ที่พยายามเข้าสู่ระบบ')),
                ('action', models.CharField(choices=[('login', 'เข้าสู่ระบบ'), ('logout', 'ออกจากระบบ'), ('login_failed', 'เข้าสู่ระบบล้มเหลว')], max_length=20, verbose_name='การดำเนินการ')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, help_text='เก็บข้อมูล Browser/Device', verbose_name='User Agent')),
                ('notes', models.TextField(blank=True, help_text='เช่น เหตุผลที่ login ล้มเหลว', verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่-เวลา')),
                ('user', models.ForeignKey(blank=True, help_text='null ได้ในกรณี login_failed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้')),
            ],
            options={
                'verbose_name': 'ประวัติการใช้งานระบบ',
                'verbose_name_plural': 'ประวัติการใช้งานระบบ',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action', 'created_at'], name='accounts_us_user_id_771d38_idx'), models.Index(fields=['action', 'created_at'], name='accounts_us_action_f244c7_idx'), models.Index(fields=['ip_address', 'created_at'], name='accounts_us_ip_addr_81e3c8_idx'), models.Index(fields=['created_at'], name='accounts_us_created_9643e0_idx')],
            },
        ),
    ]
