# Generated by Django 4.2.24 on 2025-10-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_useractivitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_number',
            field=models.CharField(blank=True, help_text='รูปแบบ: ddmmyy/xxxx เช่น 240968/0001 (ร่างยังไม่มีเลข จะได้เลขเมื่อเปลี่ยนเป็นเสร็จสิ้น)', max_length=15, null=True, unique=True, verbose_name='เลขที่ใบสำคัญรับเงิน'),
        ),
    ]
