# Generated by Django 4.2.24 on 2025-10-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_receipt_receipt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='qr_code_data',
            field=models.TextField(blank=True, help_text='ข้อมูลที่จะแสดงใน QR Code (ร่างยังไม่มี QR)', null=True, verbose_name='ข้อมูล QR Code'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='verification_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash สำหรับตรวจสอบความถูกต้อง (ร่างยังไม่มี hash)', max_length=64, null=True, unique=True, verbose_name='รหัสตรวจสอบ'),
        ),
    ]
