# Generated by Django 4.2.24 on 2025-10-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_receipt_qr_code_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่ในใบสำคัญรับเงิน'),
        ),
    ]
