# Generated by Django 4.2.24 on 2025-10-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_receipt_receipt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_number',
            field=models.CharField(blank=True, help_text='รูปแบบ: ddmmyy/xxxx เช่น 240968/0001 (ร่างยังไม่มีเลข จะได้เลขเมื่อเปลี่ยนเป็นเสร็จสิ้น)', max_length=15, null=True, verbose_name='เลขที่ใบสำคัญรับเงิน'),
        ),
        migrations.AlterUniqueTogether(
            name='receipt',
            unique_together={('receipt_number', 'department')},
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['receipt_number', 'department'], name='accounts_re_receipt_dbf01d_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['status', 'created_at'], name='accounts_re_status_4f40b9_idx'),
        ),
    ]
