# Generated by Django 4.2.24 on 2025-10-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_receipt_receipt_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipttemplate',
            name='input_type',
            field=models.CharField(choices=[('simple', 'ช่องเดียว - จำนวนเงิน'), ('textarea', 'ช่องเดียว - รายละเอียด + เงิน'), ('food_calculation', 'หลายรายการย่อย - คำนวณอัตโนมัติ')], default='simple', max_length=20, verbose_name='รูปแบบการกรอกข้อมูล'),
        ),
        migrations.AddField(
            model_name='receipttemplate',
            name='sub_items',
            field=models.JSONField(blank=True, help_text='ตัวอย่าง: {"items": [{"name": "ค่าอาหารเช้า", "fields": [...]}]}', null=True, verbose_name='รายการย่อย (JSON)'),
        ),
        migrations.AlterField(
            model_name='receipttemplate',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='เช่น 2000 บาท สำหรับค่าอาหาร หรือ 1000 บาท สำหรับค่าประกัน', max_digits=10, null=True, verbose_name='จำนวนเงินสูงสุด'),
        ),
    ]
