# Generated by Django 4.2.24 on 2025-10-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_add_template_input_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_code',
            field=models.CharField(blank=True, help_text='เก็บ student_code จาก NPU Student API', max_length=15, null=True, unique=True, verbose_name='รหัสนักศึกษา'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_degree',
            field=models.CharField(blank=True, help_text='เก็บ degree_name จาก NPU Student API', max_length=255, verbose_name='ระดับปริญญา'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_faculty',
            field=models.CharField(blank=True, help_text='เก็บ faculty_name จาก NPU Student API', max_length=255, verbose_name='คณะ'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_level',
            field=models.CharField(blank=True, help_text='เช่น ปริญญาตรี, ปริญญาโท', max_length=100, verbose_name='ระดับการศึกษา'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_program',
            field=models.CharField(blank=True, help_text='เก็บ program_name จาก NPU Student API', max_length=255, verbose_name='สาขาวิชา'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('staff', 'เจ้าหน้าที่'), ('student', 'นักศึกษา')], default='staff', help_text='ประเภทผู้ใช้ระบบ (เจ้าหน้าที่ หรือ นักศึกษา)', max_length=20, verbose_name='ประเภทผู้ใช้'),
        ),
    ]
