# Generated by Django 4.2.24 on 2025-10-19 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_user_student_code_user_student_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_by_user',
            field=models.ForeignKey(blank=True, help_text='ผู้ใช้ที่สร้าง user นี้ (สำหรับ manual creation เท่านั้น)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดยผู้ใช้'),
        ),
        migrations.AddField(
            model_name='user',
            name='source',
            field=models.CharField(choices=[('npu_api', 'NPU API'), ('manual', 'Manual Creation')], default='npu_api', help_text='ระบุว่าผู้ใช้ถูกสร้างจาก NPU API หรือสร้างแบบ Manual โดย Admin', max_length=20, verbose_name='แหล่งที่มาของผู้ใช้'),
        ),
    ]
