# Generated by Django 4.2.24 on 2025-10-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_user_created_by_user_user_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptitem',
            name='additional_recipient_name',
            field=models.CharField(blank=True, help_text='ใช้สำหรับ template รับเงินอื่นๆ Online (ข้าพเจ้า ...)', max_length=255, null=True, verbose_name='ชื่อผู้รับเงินเพิ่มเติม'),
        ),
        migrations.AlterField(
            model_name='receipttemplate',
            name='input_type',
            field=models.CharField(choices=[('simple', 'ช่องเดียว - จำนวนเงิน'), ('textarea', 'ช่องเดียว - รายละเอียด + เงิน'), ('food_calculation', 'หลายรายการย่อย - คำนวณอัตโนมัติ'), ('online_other', 'รับเงินอื่นๆ Online - รายละเอียด + ข้าพเจ้า')], default='simple', max_length=20, verbose_name='รูปแบบการกรอกข้อมูล'),
        ),
    ]
