# Generated by Django 4.2.24 on 2025-11-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_receiptitem_additional_recipient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(help_text='ชื่อย่อที่จะใช้ในใบสำคัญรับเงิน (หลายหน่วยงานสามารถใช้ชื่อย่อเดียวกันได้)', max_length=20, verbose_name='ชื่อย่อหน่วยงาน'),
        ),
    ]
