# Generated by Django 4.2.24 on 2025-11-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_department_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptitem',
            name='description',
            field=models.CharField(help_text='คำอธิบายรายการ', max_length=2000, verbose_name='รายการ'),
        ),
    ]
