# Generated by Django 4.2.24 on 2026-08-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_receiptitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(choices=[('login', 'เข้าสู่ระบบ'), ('logout', 'ออกจากระบบ'), ('login_failed', 'เข้าสู่ระบบล้มเหลว'), ('npu_resync', 'ดึงข้อมูลจาก NPU ใหม่')], max_length=20, verbose_name='การดำเนินการ'),
        ),
    ]
